### ISSUE TITLE
Fix label layer bugs

### ISSUE THREAD

**Issue by PaliwalSparsh** [frictionlessweb/formpdf#34]
Label layer has many bugs. Update label is available on both label and field. Currently, update label/delete on the field box deletes the field box. Also, we can have two labels for one field bo
<img width="342" alt="Screen Shot 2022-05-16 at 7 52 54 AM" src="https://user-images.githubusercontent.com/6324861/168621470-d8657cb6-0236-4317-b4b9-a858c9cfdb7a.png">
x

**Comment by joshuaharry** [comment]
I think this is solved! Is there more to do?

**Comment by PaliwalSparsh** [comment]
Currently, we get different action menus when clicking on label and annotation. The position of the action menu should always be where the box is and the action menu should have both options – "Update label" and "Delete".
<img width="657" alt="Screen Shot 2022-05-17 at 2 05 01 PM" src="https://user-images.githubusercontent.com/6324861/168910041-0b63ee85-931a-4127-a83c-c2397037185c.png">

<img width="658" alt="Screen Shot 2022-05-17 at 2 05 11 PM" src="https://user-images.githubusercontent.com/6324861/168910067-b8496de6-fc02-4979-b50e-0c30d4e1f2f1.png">

Apart from that everything's fixed. We can look into this part later.
