### ISSUE TITLE
Fix group layer bugs

### ISSUE THREAD

**Issue by PaliwalSparsh** [frictionlessweb/formpdf#35]
<img width="342" alt="Screen Shot 2022-05-16 at 7 53 30 AM" src="https://user-images.githubusercontent.com/6324861/168621601-af371038-bdf7-4cd0-81e2-9935a7e2606f.png">

**Comment by joshuaharry** [comment]
Will be closed with https://github.com/frictionlessweb/formpdf/pull/39
